INSERT INTO Probe(probeId,probeName,password,salt,token) VALUES (1,"probe Wildfly WSVD", "n/a","n/a","n/a");
INSERT INTO Probe(probeId,probeName,password,salt,token) VALUES (2,"probe MySQL WSVD", "n/a","n/a","n/a");
INSERT INTO Probe(probeId,probeName,password,salt,token) VALUES (3,"probe Demo Java", "n/a","n/a","n/a");
INSERT INTO Probe(probeId,probeName,password,salt,token) VALUES (4,"probe Demo Python", "n/a","n/a","n/a");
INSERT INTO Probe(probeId,probeName,password,salt,token) VALUES (5,"probe Docker", "n/a","n/a","n/a");
INSERT INTO Probe(probeId,probeName,password,salt,token) VALUES (6,"probe Kubernetes", "n/a","n/a","n/a");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (1,"CPU_Usage", "measurement","Mi");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (2,"Memory", "measurement","Bytes");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (3,"Disk", "event","n/a");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (4,"CPU_Usage", "measurement","Mi");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (5,"Memory", "measurement","Bytes");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (6,"Disk", "event","n/a");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (7,"CPU_Usage", "measurement","Mi");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (8,"Memory", "measurement","Bytes");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (9,"Disk", "event","n/a");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (10,"CPU_Usage", "measurement","Mi");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (11,"Memory", "measurement","Bytes");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (12,"Disk", "event","n/a");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (13,"Memory", "event","n/a");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (14,"CPU_Usage", "measurement","Mi");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (15,"Memory", "measurement","Bytes");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (16,"Disk", "event","n/a");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (17,"CPU_Usage", "measurement","Mi");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (18,"Memory", "measurement","Bytes");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (19,"Disk", "event","n/a");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (20,"CPU_Usage", "measurement","Mi");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (21,"Memory", "measurement","Bytes");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (22,"Disk", "event","n/a");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (23,"CPU_Usage", "measurement","Mi");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (24,"Memory", "measurement","Bytes");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (25,"Disk", "event","n/a");
INSERT INTO Description(descriptionId,dataType,descriptionName,unit) VALUES (26,"Memory", "event","n/a");
INSERT INTO Resource(resourceId,resourceName,resourceType,resourceAddress) VALUES (1,"VM_VIRT_NODE", "VM","n/a");
INSERT INTO Resource(resourceId,resourceName,resourceType,resourceAddress) VALUES (2,"Pod Apache Flume", "POD","n/a");
INSERT INTO Resource(resourceId,resourceName,resourceType,resourceAddress) VALUES (3,"VM_VIRT_MASTER", "VM","n/a");
INSERT INTO Resource(resourceId,resourceName,resourceType,resourceAddress) VALUES (4,"Pod MySQL", "POD","n/a");
INSERT INTO Resource(resourceId,resourceName,resourceType,resourceAddress) VALUES (5,"Pod Apache Zookeeper", "POD","n/a");
INSERT INTO Resource(resourceId,resourceName,resourceType,resourceAddress) VALUES (6,"Pod Apache Kafka", "POD","n/a");
INSERT INTO Resource(resourceId,resourceName,resourceType,resourceAddress) VALUES (7,"Pod Monitor", "POD","n/a");
