--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- ATMOSPHERE - http://www.atmosphere-eubrazil.eu/
-- 
-- 
-- Trustworthiness Monitoring & Assessment Framework
-- Component: Knowledge - database
-- 
-- Repository: https://github.com/eubr-atmosphere/tma-framework
-- License: https://github.com/eubr-atmosphere/tma-framework/blob/master/LICENSE
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--
-- Raw file as generated by astah. 
-- Check TMA-K_create_database.sql for the normalized MySQL version.
--
--
-- @author José Pereira <josep@dei.uc.pt>
-- @author Nuno Antunes <nmsa@dei.uc.pt>
-- 
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

DROP TABLE Actuator CASCADE CONSTRAINTS;
CREATE TABLE Actuator (
 actuatorId INT NOT NULL PRIMARY KEY,
 address VARCHAR(1024),
 pubKey VARCHAR(1024)
);


DROP TABLE Description CASCADE CONSTRAINTS;
CREATE TABLE Description (
 descriptionId INT NOT NULL PRIMARY KEY,
 dataType CHAR(16),
 descriptionName CHAR(128),
 unit CHAR(16)
);


DROP TABLE Probe CASCADE CONSTRAINTS;
CREATE TABLE Probe (
 probeId INT NOT NULL PRIMARY KEY,
 probeName VARCHAR(128),
 password VARCHAR(128),
 salt VARCHAR(128) NOT NULL,
 token VARCHAR(256),
 tokenExpiration TIMESTAMP(6)
);


DROP TABLE Resource CASCADE CONSTRAINTS;
CREATE TABLE Resource (
 resourceId INT NOT NULL PRIMARY KEY,
 resourceName VARCHAR(128),
 resourceType VARCHAR(16),
 resourceAddress VARCHAR(1024)
);


DROP TABLE Time CASCADE CONSTRAINTS;
CREATE TABLE Time (
 valueTime TIMESTAMP(6) NOT NULL PRIMARY KEY
);


DROP TABLE Action CASCADE CONSTRAINTS;
CREATE TABLE Action (
 actionId INT NOT NULL PRIMARY KEY,
 actuatorId INT NOT NULL,
 resourceId INT NOT NULL,
 actionName VARCHAR(128),

 FOREIGN KEY (actuatorId) REFERENCES Actuator (actuatorId),
 FOREIGN KEY (resourceId) REFERENCES Resource (resourceId)
);


DROP TABLE Configuration CASCADE CONSTRAINTS;
CREATE TABLE Configuration (
 actionId INT NOT NULL PRIMARY KEY,
 keyName VARCHAR(128),
 domain VARCHAR(1024),

 FOREIGN KEY (actionId) REFERENCES Action (actionId)
);


DROP TABLE Data CASCADE CONSTRAINTS;
CREATE TABLE Data (
 probeId INT NOT NULL,
 descriptionId INT NOT NULL,
 resourceId INT NOT NULL,
 valueTime TIMESTAMP(6) NOT NULL,
 value DOUBLE PRECISION,

 PRIMARY KEY (probeId,descriptionId,resourceId,valueTime),

 FOREIGN KEY (probeId) REFERENCES Probe (probeId),
 FOREIGN KEY (descriptionId) REFERENCES Description (descriptionId),
 FOREIGN KEY (resourceId) REFERENCES Resource (resourceId),
 FOREIGN KEY (valueTime) REFERENCES Time (valueTime)
);


