apiVersion: v1
kind: Service
metadata:
  name: tma-admin-web
  labels:
    app: tma-admin-web
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32027
  clusterIP: 10.100.112.116
  selector:
    app: tma-admin-web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tma-admin-web
spec:
  selector:
    matchLabels:
      app: tma-admin-web # has to match .spec.template.metadata.labels
  serviceName: "tma-admin-web"
  template:
    metadata:
      labels:
        app: tma-admin-web # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: tma-admin-web
        image: tma-admin-web:0.1