apiVersion: apps/v1
kind: Deployment

metadata:
  name: tma-admin-console

spec:
  selector:
    matchLabels:
      run: tma-admin-console
  template:
    metadata:
      labels:
        run: tma-admin-console
    spec:
      containers:
      - name: tma-admin
        image: tma-admin:0.1
